### ISSUE TITLE
FV: Ownership update after finalization

### ISSUE THREAD

**Issue by remedcu** [5afe/CandideWalletContracts#8] opened 2024-05-03 11:54 UTC
## Intention

> After finalization of recovery, old owners should be replaced/removed and new owners should be present in Safe Wallet. (Change of threshold also could be checked)

## Description

The Recovery Module removes all the current owners, and replaces it with the new set of owners passed at the time of recovery initiation. We should check the following:
- All the previous owners were removed.
- All the new owners were added.
- Change of threshold (if any)

## Expected Outcome

Rules to verify the above mentioned requirements are met when a recovery is finalized.

Note: There could be a case where the same owners are added again in FV (though in real world, it makes no sense).

**Comment by nlordell** [comment] 2024-06-21 08:19
This is currently blocked as we are running into issues with the Certora prover. @akshay-ap - can you add more details about the exact nature of the issue here?

**Comment by akshay-ap** [comment] 2024-06-21 12:47
The issue is blocked by the issues below:
1. prover reporting error when using quantifier

The quantifier below aims at having distinct addressed in new owners and existing safe owners list. Having new owners as existing Safe owner in recovery is not expected. Also, prover config has `loop_iter` value less than or equal to `3` due to computation complexity and thus, verification for recovery of Safe with larger threshold and just replacing few owners with new addresses is not considered.

`require forall uint256 y2. forall uint256 x2. y2 < ownersBefore.length && x2 < newOwnersCount => newOwners[x2] != ownersBefore[y2];`

Error:

<img width="1328" alt="Screenshot 2024-06-21 at 14 41 33" src="https://github.com/5afe/CandideWalletContracts/assets/16358982/918dab3c-9dc1-4b3b-ada9-4e8222bef0ef">



2. While verifying ownership of Safe after successful recovery, the prover reports invalid counter examples. Reachability related invariants have been imported from [OwnerReach.spec ](https://github.com/safe-global/safe-smart-account/blob/main/certora/specs/OwnerReach.spec) to remove these invalid counter examples. But, prover runs into timeout issues even when using `loop_iter=3`.

https://prover.certora.com/output/8584/290728acd72642c0b3269f3614fdf1f8?anonymousKey=692ed28f8a2fa815969d07a417cf314a4e6e3f7e

**Comment by nlordell** [comment] 2024-07-22 11:33
This issue is once again blocked, so removing from the sprint.

**Closed as completed** 2024-08-08 08:39 UTC
Labels: fv
